- name : play level variables
  hosts: local
  connection : local
  vars_file:
  - course.yaml
  tasks:
   - name : print variables
     ansible.builtin.debug:  
       msg: "course is : {{COURSE}},  trainer is: {{TRAINER}}, duration is : {{DURATION}}"